// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcrQTrl4kCFNQ09h3O4iL6hlrZTLIWNY',
    appId: '1:606669099034:web:e5e3db2eea6b07cdbb41a3',
    messagingSenderId: '606669099034',
    projectId: 'circlebook-ssj',
    authDomain: 'circlebook-ssj.firebaseapp.com',
    storageBucket: 'circlebook-ssj.appspot.com',
    measurementId: 'G-PS6YBMBWMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPE4vUYSP7jW_BjJCVR8sKszeyPzGg3ik',
    appId: '1:606669099034:android:d7e50161ef31113dbb41a3',
    messagingSenderId: '606669099034',
    projectId: 'circlebook-ssj',
    storageBucket: 'circlebook-ssj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2bALoheykCiq4dB_XnZCf-BHOVrrwHvU',
    appId: '1:606669099034:ios:d8779b1d321de606bb41a3',
    messagingSenderId: '606669099034',
    projectId: 'circlebook-ssj',
    storageBucket: 'circlebook-ssj.appspot.com',
    iosClientId: '606669099034-792sck8ubklefk7odknm8cms637cuv5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.circleBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2bALoheykCiq4dB_XnZCf-BHOVrrwHvU',
    appId: '1:606669099034:ios:54244e1b90aa44f4bb41a3',
    messagingSenderId: '606669099034',
    projectId: 'circlebook-ssj',
    storageBucket: 'circlebook-ssj.appspot.com',
    iosClientId: '606669099034-hfso26rap87eltlo3gh0b6610nj3budu.apps.googleusercontent.com',
    iosBundleId: 'com.example.circleBook.RunnerTests',
  );
}
